### ISSUE TITLE
`sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Attempt at 0x45e7c90> is not bound to a Session`

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#175]
``` python
Traceback (most recent call last):
  File "validator.py", line 609, in <module>
    results = [msg for msg in ppl.run(messages)]
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 150, in run
    for out_data in iterable:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 97, in __iter__
    for data in self._iterable_data:
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 98, in __iter__
    yield self.transform(data)
  File "/home/gustavo/.virtualenvs/balaio/src/plumber/plumber.py", line 61, in decorated
    return f(instance, data)
  File "validator.py", line 74, in transform
    if attempt.articlepkg.issue_volume:
  File "/home/gustavo/.virtualenvs/balaio/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 316, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/gustavo/.virtualenvs/balaio/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 613, in get
    value = self.callable_(state, passive)
  File "/home/gustavo/.virtualenvs/balaio/local/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 497, in _load_for_state
    (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Attempt at 0x45e7c90> is not bound to a Session; lazy load operation of attribute 'articlepkg' cannot proceed
```

**Comment by gustavofonseca** [comment]
Este ticket é resolvido com o PR #176
