### ISSUE TITLE
Erro ao validar o título NLM

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#254]
Erro ao tentar realizar a validação com um pacote, segue traceback:

``` python
2014-02-21 20:06:08,291 - DEBUG - 6190 - 140376940287744 - vpipes - NLMJournalTitleValidationPipe started processing <Attempt('24, b719eaa363d4cd4b65430d5e7357647f6ea30726')>
Traceback (most recent call last):
  File "validator.py", line 633, in <module>
    for msg in ppl.run(messages):
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 166, in run
    for out_data in iterable:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 113, in __iter__
    for data in self._iterable_data:
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 114, in __iter__
    yield self.transform(data)
  File "/home/jamil/.virtualenvs/balaio-env/src/plumber/plumber.py", line 77, in decorated
    return f(instance, data)
  File "/home/jamil/balaio/balaio/vpipes.py", line 43, in transform
    result_status, result_description = self.validate(item)
  File "validator.py", line 429, in validate
    if self._normalize_data(xml_nlm_title) == self._normalize_data(j_nlm_title):
  File "/home/jamil/balaio/balaio/utils.py", line 268, in normalize_data
    return ' '.join(data.upper().split())
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by fabiobatalha** [comment]
Referente ao #255
